version: "3"
services:
  amqp:
    image: rabbitmq:3.8-management
    ports:
    - "5672:5672"
    - "15672:15672"
  prometheus:
    network_mode: host
    image: prom/prometheus
    volumes:
    - ./prometheus:/etc/prometheus/